name: GitHub Deploy YandexCloud
on:
  push:
    branches:
      - main
      - dev
      - feat/#8
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy service on VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Copy code to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "src"
          target: /home/${{ secrets.SSH_USERNAME }}/librareally

      # - name: Run app on VM
      #   uses: appleboy/ssh-action@v1.0.0
      #   env:
      #     WAIT_PORTS: 8080,8070,8060,8050
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd /home/${{ secrets.SSH_USERNAME }}/library_system_lab03
      #       echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose down
      #       echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi gateway_service_lab03
      #       echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi library_service_lab03
      #       echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi reservation_service_lab03
      #       echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi rating_service_lab03
      #       echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose up -d
      #       echo ${{ secrets.SSH_PASSWORD }} | sudo ./scripts/wait-script.sh
